### ISSUE TITLE
 Can't get balance

### ISSUE THREAD

**Issue by trien-tran** [suiet/wallet-kit#173] opened 2023-05-18 02:16 UTC
I always get zero balance even though my wallet still have money, a few days ago it still shows the balance, anyone know what the problem is?

**Comment by bruceeewong** [comment] 2023-05-18 13:05
@trien-tran Looks like the change of RPC rpc.mainnet.sui.io leads to CORS forbiddance on the browser. Will look at this problem and fix it soon

**Comment by bruceeewong** [comment] 2023-05-19 03:37
@trien-tran I've confirmed with Sui team that there is a bug of RPC where the prefix of Sui coin type changed from 0x2 to 0x0000...2, which led to the failure to get the accurate balance. It should be fixed in the next 1.1.1 hotfix version of Sui Node, please wait until they fix it.

**Comment by ser25** [comment] 2023-05-19 13:31
how fix

**Comment by bruceeewong** [comment] 2023-05-20 03:47
@trien-tran @ser25 Now the Sui RPC has fixed the issue. Everything should work well now

**Closed** 2023-05-25 01:12 UTC
